/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CLIMATE_CLIMATE_READING_PB_H_INCLUDED
#define PB_CLIMATE_CLIMATE_READING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _climate_ClimateReading {
    uint32_t device_id; /* short numeric ID */
    uint32_t ts_ms; /* timestamp (ms or seconds, your choice) */
    uint32_t mq135_ppm; /* air quality */
    uint32_t water_level_mm; /* water level in mm */
    uint32_t rain_intensity_x10; /* rain intensity * 10 */
    uint32_t battery_mv; /* battery voltage * 1000 (mV) */
    int32_t lat_e7; /* latitude * 1e7 */
    int32_t lon_e7; /* longitude * 1e7 */
} climate_ClimateReading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define climate_ClimateReading_init_default      {0, 0, 0, 0, 0, 0, 0, 0}
#define climate_ClimateReading_init_zero         {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define climate_ClimateReading_device_id_tag     1
#define climate_ClimateReading_ts_ms_tag         2
#define climate_ClimateReading_mq135_ppm_tag     3
#define climate_ClimateReading_water_level_mm_tag 4
#define climate_ClimateReading_rain_intensity_x10_tag 5
#define climate_ClimateReading_battery_mv_tag    6
#define climate_ClimateReading_lat_e7_tag        7
#define climate_ClimateReading_lon_e7_tag        8

/* Struct field encoding specification for nanopb */
#define climate_ClimateReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   ts_ms,             2) \
X(a, STATIC,   SINGULAR, UINT32,   mq135_ppm,         3) \
X(a, STATIC,   SINGULAR, UINT32,   water_level_mm,    4) \
X(a, STATIC,   SINGULAR, UINT32,   rain_intensity_x10,   5) \
X(a, STATIC,   SINGULAR, UINT32,   battery_mv,        6) \
X(a, STATIC,   SINGULAR, SINT32,   lat_e7,            7) \
X(a, STATIC,   SINGULAR, SINT32,   lon_e7,            8)
#define climate_ClimateReading_CALLBACK NULL
#define climate_ClimateReading_DEFAULT NULL

extern const pb_msgdesc_t climate_ClimateReading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define climate_ClimateReading_fields &climate_ClimateReading_msg

/* Maximum encoded size of messages (where known) */
#define CLIMATE_CLIMATE_READING_PB_H_MAX_SIZE    climate_ClimateReading_size
#define climate_ClimateReading_size              48

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
