/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CLIMATE_SENSOR_PB_H_INCLUDED
#define PB_CLIMATE_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Uplink from ESP32-S3 LoRa node */
typedef struct _climate_SensorReading {
    /* Environmental */
    float temperature_c;
    float humidity_percent;
    float pressure_hpa;
    /* Air / water sensors */
    float air_quality_raw;
    float rain_level_raw;
    float water_level_raw;
    /* Power */
    uint32_t battery_mv;
    /* GNSS */
    bool gnss_enabled;
    bool gnss_fix_valid;
    double latitude_deg;
    double longitude_deg;
    float altitude_m;
    float hdop;
    /* Meta */
    uint64_t timestamp_ms;
    /* ⭐ Add this */
    uint32_t device_id;
} climate_SensorReading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define climate_SensorReading_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define climate_SensorReading_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define climate_SensorReading_temperature_c_tag  1
#define climate_SensorReading_humidity_percent_tag 2
#define climate_SensorReading_pressure_hpa_tag   3
#define climate_SensorReading_air_quality_raw_tag 4
#define climate_SensorReading_rain_level_raw_tag 5
#define climate_SensorReading_water_level_raw_tag 6
#define climate_SensorReading_battery_mv_tag     7
#define climate_SensorReading_gnss_enabled_tag   8
#define climate_SensorReading_gnss_fix_valid_tag 9
#define climate_SensorReading_latitude_deg_tag   10
#define climate_SensorReading_longitude_deg_tag  11
#define climate_SensorReading_altitude_m_tag     12
#define climate_SensorReading_hdop_tag           13
#define climate_SensorReading_timestamp_ms_tag   14
#define climate_SensorReading_device_id_tag      15

/* Struct field encoding specification for nanopb */
#define climate_SensorReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity_percent,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure_hpa,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    air_quality_raw,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    rain_level_raw,    5) \
X(a, STATIC,   SINGULAR, FLOAT,    water_level_raw,   6) \
X(a, STATIC,   SINGULAR, UINT32,   battery_mv,        7) \
X(a, STATIC,   SINGULAR, BOOL,     gnss_enabled,      8) \
X(a, STATIC,   SINGULAR, BOOL,     gnss_fix_valid,    9) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude_deg,     10) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude_deg,    11) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude_m,       12) \
X(a, STATIC,   SINGULAR, FLOAT,    hdop,             13) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,     14) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,        15)
#define climate_SensorReading_CALLBACK NULL
#define climate_SensorReading_DEFAULT NULL

extern const pb_msgdesc_t climate_SensorReading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define climate_SensorReading_fields &climate_SensorReading_msg

/* Maximum encoded size of messages (where known) */
#define CLIMATE_SENSOR_PB_H_MAX_SIZE             climate_SensorReading_size
#define climate_SensorReading_size               85

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
