/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_SENSOR_READING_PB_H_INCLUDED
#define PB_PROTO_SENSOR_READING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorReading {
    char device_id[32];
    int64_t timestamp_ms;
    float temperature_c;
    float humidity_pct;
    float pressure_hpa;
    float mq135_ppm;
    float rain_level;
    float water_level;
    bool is_virtual;
} SensorReading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorReading_init_default               {"", 0, 0, 0, 0, 0, 0, 0, 0}
#define SensorReading_init_zero                  {"", 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorReading_device_id_tag              1
#define SensorReading_timestamp_ms_tag           2
#define SensorReading_temperature_c_tag          3
#define SensorReading_humidity_pct_tag           4
#define SensorReading_pressure_hpa_tag           5
#define SensorReading_mq135_ppm_tag              6
#define SensorReading_rain_level_tag             7
#define SensorReading_water_level_tag            8
#define SensorReading_is_virtual_tag             9

/* Struct field encoding specification for nanopb */
#define SensorReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_ms,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity_pct,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure_hpa,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    mq135_ppm,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    rain_level,        7) \
X(a, STATIC,   SINGULAR, FLOAT,    water_level,       8) \
X(a, STATIC,   SINGULAR, BOOL,     is_virtual,        9)
#define SensorReading_CALLBACK NULL
#define SensorReading_DEFAULT NULL

extern const pb_msgdesc_t SensorReading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorReading_fields &SensorReading_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_SENSOR_READING_PB_H_MAX_SIZE       SensorReading_size
#define SensorReading_size                       76

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
