[env:esp32s3_loranode]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=1

lib_deps =
  adafruit/Adafruit BME280 Library
  adafruit/Adafruit Unified Sensor
  mikalhart/TinyGPSPlus
  sandeepmistry/LoRa