# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x07\x63limate\"\xda\x02\n\rSensorReading\x12\x15\n\rtemperature_c\x18\x01 \x01(\x02\x12\x18\n\x10humidity_percent\x18\x02 \x01(\x02\x12\x14\n\x0cpressure_hpa\x18\x03 \x01(\x02\x12\x17\n\x0f\x61ir_quality_raw\x18\x04 \x01(\x02\x12\x16\n\x0erain_level_raw\x18\x05 \x01(\x02\x12\x17\n\x0fwater_level_raw\x18\x06 \x01(\x02\x12\x12\n\nbattery_mv\x18\x07 \x01(\r\x12\x14\n\x0cgnss_enabled\x18\x08 \x01(\x08\x12\x16\n\x0egnss_fix_valid\x18\t \x01(\x08\x12\x14\n\x0clatitude_deg\x18\n \x01(\x01\x12\x15\n\rlongitude_deg\x18\x0b \x01(\x01\x12\x12\n\naltitude_m\x18\x0c \x01(\x02\x12\x0c\n\x04hdop\x18\r \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x0e \x01(\x04\x12\x11\n\tdevice_id\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREADING']._serialized_start=26
  _globals['_SENSORREADING']._serialized_end=372
# @@protoc_insertion_point(module_scope)
