apiVersion: 1

datasources:
  - name: ClimateDB
    type: postgres
    access: proxy
    url: db:5432
    user: climate
    secureJsonData:
      password: climate_password
    jsonData:
      database: climate_db
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true