apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: climate
      sslmode: disable